Controllers/MasterArtikelController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MandiriCRE.Models;
using MandiriCRE.Properties;
using System.Configuration;

namespace MandiriCRE.Controllers
{
    public class MasterArtikelController : Controller
    {
        // GET: MasterArtikel
        public ActionResult Index1()
        {
            return View();
        }
        string Baseurl = Properties.Settings.Default.BaseURI;
        public async Task<ActionResult> Index()
        {
            List<Articles> objInfo = new List<Articles>();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllEmployees using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.ArticleAPI);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<List<Articles>>(APIResponse);

                }
                //returning the employee list to view  
                return View(objInfo);
            }
        }
        // GET: MasterArtikel/Details/5
        public async Task<ActionResult> Details(int id)
        {
            Articles objInfo = new Articles();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.ArticleAPI + "/" + id);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<Articles>(APIResponse);

                }
                //returning the employee list to view  
                return View(objInfo);
            }
        }

        // GET: MasterArtikel/Create
        public ActionResult Create()
        {
            Articles objInfo = new Articles();
            return View(objInfo);
        }

        // POST: MasterArtikel/Create
        [HttpPost]
        public async Task<ActionResult> Create(Articles obj, FormCollection form)
        {
            try
            {
                obj.Headline = form["headline"].ToString();
                obj.Content = form["content"].ToString();
                obj.Position =  form["position"].ToString();
                obj.ValidFrom = form["startdate"].ToString();
                obj.ValidTo = form["finishdate"].ToString();
                obj.UpdatedBy = User.Identity.Name;
                obj.UpdatedDate = DateTime.Now.ToString("dd/MM/yyyy");
                obj.CreatedBy = User.Identity.Name;
                obj.CreatedDate = DateTime.Now.ToString("dd/MM/yyyy");
                obj.UpdateBy = User.Identity.Name;
                obj.CreateBy = User.Identity.Name;
                // TODO: Add update logic here
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                // TODO: Add update logic here
                HttpResponseMessage response = await client.PostAsJsonAsync(Properties.Settings.Default.ArticleAPI, obj);
                response.EnsureSuccessStatusCode();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string err = ex.Message.ToString();
                return View();
            }
        }

        // GET: MasterArtikel/Edit/5
        public async Task<ActionResult> Edit(int id)
        {
            Articles objInfo = new Articles();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.ArticleAPI + "/" + id);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<Articles>(APIResponse);

                }
                //returning the employee list to view  
                return View(objInfo);
            }
        }

        // POST: MasterArtikel/Edit/5
        [HttpPost]
        public async Task<ActionResult> Edit(int id, Articles obj, FormCollection form)
        {
            try
            {
                obj.Headline = form["headline"].ToString();
                obj.Content = form["content"].ToString();
                obj.Position =  form["position"].ToString();
                obj.ValidFrom = form["startdate"].ToString();
                obj.ValidTo = form["finishdate"].ToString();
                obj.UpdatedBy = User.Identity.Name;
                obj.UpdatedDate = DateTime.Now.ToString("dd/MM/yyyy");
                obj.NewsID = id.ToString();
                obj.UpdateBy = User.Identity.Name;
                // TODO: Add update logic here
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                // TODO: Add update logic here
                HttpResponseMessage response = await client.PutAsJsonAsync(Properties.Settings.Default.ArticleAPI + "/" + id, obj);
                response.EnsureSuccessStatusCode();
                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string err = ex.Message.ToString();
                return View();
            }
        }

        // GET: MasterArtikel/Delete/5
        public async Task<ActionResult> Delete(int id)
        {
            Articles objInfo = new Articles();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.ArticleAPI + "/" + id);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<Articles>(APIResponse);

                }
                //returning the employee list to view  
                return View(objInfo);
            }
        }

        // POST: MasterArtikel/Delete/5
        [HttpPost]
        public async Task<ActionResult> Delete(int id, Articles obj)
        {
            // TODO: Add delete logic here
            try
            {
                // TODO: Add update logic here
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri(Baseurl);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));
                // TODO: Add update logic here

Views/MasterArtikel/Create.cshtml
@model MandiriCRE.Models.Articles

@{
    ViewBag.Title = "Create";
}

<h2></h2>
 <!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
    <!-- widget options:
        usage: <div class="jarviswidget" id="wid-id-0" data-widget-editbutton="false">

        data-widget-colorbutton="false"
        data-widget-editbutton="false"
        data-widget-togglebutton="false"
        data-widget-deletebutton="false"
        data-widget-fullscreenbutton="false"
        data-widget-custombutton="false"
        data-widget-collapsed="true"
        data-widget-sortable="false"

    -->
    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
        <h2> </h2>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            @using (Html.BeginForm("Create", "MasterArtikel",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "smart-form", @id = "News-form" }))
            {
                @*etc.
}
            <form id="order-form" class="smart-form" novalidate="novalidate">*@

                <header>
                    Tambah Artikel
                </header>

                <fieldset>           
                    <section>
                        <label>Judul Berita*</label>
                        <label class="textarea">
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="2" name="headline" id="headline" maxlength="50" placeholder="">@Model.Headline</textarea>
                        </label>
                    </section>
                    <section>
                        <label>Isi Berita*</label>
                        <label class="textarea">
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="5" name="content" id="content" maxlength="250" placeholder="">@Model.Content</textarea>
                        </label>
                    </section>
                    <div class="row">
                        <section class="col col-6">
                            <label>Status*</label>
                            <label class="select">
                                <select name="position" id="position">
                                    <option value="0" selected="" disabled="">(Active/Inactive)</option>
                                    <option value="Y">Active</option>
                                    <option value="T">Inactive</option>
                                </select> <i></i>
                            </label>
                        </section>
                        </div>
                    <div class="row" style="display:none;">
                        <section class="col col-6">
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <input type="text" name="startdate" id="startdate" value="@Model.ValidFrom" placeholder="Expected Valid From date">
                            </label>
                        </section>
                        <section class="col col-6" style="display:none;">
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <input type="text" name="finishdate" id="finishdate" value="@Model.ValidTo" placeholder="Expected Valid To date">
                            </label>
                        </section>
                    </div>
                </fieldset>
                <footer>
    
                    <input type="submit" value="Simpan" class="btn btn-primary" />
                    <button type="button" class="btn btn-default" onclick="window.history.back();">Batal</button>
                </footer>
            }
            @*</form>*@

        </div>
        <!-- end widget content -->

    </div>
    <!-- end widget div -->

</div>
<!-- end widget -->



@section pagespecific {
    <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function () {

        // PAGE RELATED SCRIPTS

        // class switcher for radio and checkbox
        $('input[name="demo-switcher-1"]').change(function () {
            //alert($(this).val())
            $this = $(this);

            myNewClass = $this.attr('id');

            $('.demo-switcher-1 input[type="checkbox"]').removeClass();
            $('.demo-switcher-1 input[type="checkbox"]').addClass("checkbox " + myNewClass);

            $('.demo-switcher-1 input[type="radio"]').removeClass();
            $('.demo-switcher-1 input[type="radio"]').addClass("radiobox " + myNewClass);

        })

    })
    $(document).ready(function () {

        var $checkoutForm = $('#News-form').validate({
            // Rules for form validation
            rules: {
                headline: {
                    required: true,
                    maxlength: 50
                },
                content: {
                    required: true,
                    maxlength: 250
                },
                position: {
                    required: true
                }
            },

            // Messages for form validation
            messages: {
                headline: {
                    required: 'Silahkan isi Judul Berita'
                },
                content: {
                    required: 'Silahkan isi Berita'
                },
                position: {
                    required: 'Silahkan pilih Status'
                    
                }
            },

            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });

        // START AND FINISH DATE
        $('#startdate').datepicker({
            dateFormat: 'dd/mm/yy',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (selectedDate) {
                $('#finishdate').datepicker('option', 'minDate', selectedDate);
            }
        });

        $('#finishdate').datepicker({
            dateFormat: 'dd/mm/yy',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (selectedDate) {
                $('#startdate').datepicker('option', 'maxDate', selectedDate);
            }
        });

        var $orderForm = $("#order-form").validate({
            // Rules for form validation
            rules: {
                name: {
                    required: true
                },
                email: {
                    required: true,
                    email: true
                },
                phone: {
                    required: true
                },
                interested: {
                    required: true
                },
                budget: {
                    required: true
                },
                startdate: {
                    required: true
                },
                finishdate: {
                    required: true
                },
                headline: {
                    required: true
                },
                content: {
                    required: true
                },
            },

            // Messages for form validation
            messages: {
                name: {
                    required: 'Please enter your name'
                },
                email: {
                    required: 'Please enter your email address',
                    email: 'Please enter a VALID email address'
                },
                phone: {
                    required: 'Please enter your phone number'
                },
                interested: {
                    required: 'Please select interested service'
                },
                budget: {
                    required: 'Please select your budget'
                },
                startdate: {
                    required: 'Please select Valid From Date'
                },
                finishdate: {
                    required: 'Please select Valid From Date'
                },
                headline: {
                    required: 'Please enter your headline'
                },
                content: {
                    required: 'Please input your content'
                }
            },
            // Ajax form submition
            //submitHandler: function (form) {
            //    $(form).ajaxSubmit({
            //        success: function () {
            //            $("#order-form").addClass('submited');
            //        }
            //    });
            //},
            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });

        


    })
    </script>
}

Views/MasterArtikel/Delete.cshtml
@model MandiriCRE.Models.Articles

@{
    ViewBag.Title = "Delete";
}

<br />


<!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">

    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            @using (Html.BeginForm("Delete", "MasterArtikel",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "smart-form", @id = "article-form" }))
            {
                <header>
                    <b> Apakah Anda yakin akan menghapus data ini ?</b>
                </header>
                <fieldset>
                    <section>
                        <label>Judul Berita</label>
                        <label class="textarea">
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="2" name="headline" disabled="disabled" placeholder="">@Model.Headline</textarea>
                        </label>
                    </section>
                    <section>
                        <label>Isi Berita</label>
                        <label class="textarea">
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="5" name="content" disabled="disabled" placeholder="">@Model.Content</textarea>
                        </label>
                    </section>
                    <div class="row">
                        <section class="col col-6" style="display:none;">
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <input type="text" name="startdate" id="startdate" value="@Model.ValidFrom"  disabled="disabled" placeholder="Expected Valid From date">
                            </label>
                        </section>
                        <section class="col col-6" style="display:none;">
                            <label class="input">
                                <i class="icon-append fa fa-calendar"></i>
                                <input type="text" name="finishdate" id="finishdate" value="@Model.ValidTo"  disabled="disabled" placeholder="Expected Valid To date">
                            </label>
                        </section>
                    </div>
                    <div class="row">
                        <section class="col col-6">
                            <label>Status</label>
                            <label class="input">
                                <input type="text" name="Position" id="Position" value="@Model.Position"  disabled="disabled" placeholder="">
                            </label>
                        </section>
                    </div>
                </fieldset>
                <footer>


                    <input type="submit" value="Hapus" class="btn btn-primary btn-lg" />

                    @*<input type="submit" value="Save" class="btn btn-primary" />*@
                    <button type="button" class="btn btn-default" onclick="window.history.back();">Batal</button>
                    @Html.AntiForgeryToken()


                </footer>
            }
            @*</form>*@

        </div>
        <!-- end widget content -->

    </div>
    <!-- end widget div -->

</div>
<!-- end widget -->

Views/MasterArtikel/Details.cshtml
@model MandiriCRE.Models.Articles

@{
    ViewBag.Title = "Details";
}

<h2></h2>
<!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">

    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
        <h2>Input form </h2>

    </header>

    <!-- widget div-->
    <div>

        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->

        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            @using (Html.BeginForm("Details", "MasterArtikel",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "smart-form", @id = "article-form" }))
            {

                <header>
                    Detail Article
                </header>

                <fieldset>
                    <section>
                        <label class="textarea">Headline
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="2" disabled="disabled" name="headline" placeholder="Article Headline">@Model.Headline</textarea>
                        </label>
                    </section>
                    <section>
                        <label class="textarea">Article
                            <i class="icon-append fa fa-comment"></i>
                            <textarea rows="5"  disabled="disabled" name="content" placeholder="Article Content">@Model.Content</textarea>
                        </label>
                    </section>
                    @*<div class="row">
                        <section class="col col-6">
                            <label class="input">Valid From
                                <input type="text" disabled="disabled" name="validfrom" value="@Model.ValidFrom" >
                            </label>
                        </section>
                        <section class="col col-6">
                            <label class="input">Valid To
                                <input type="text"  disabled="disabled" name="validto" value="@Model.ValidTo">
                            </label>
                        </section>
                    </div>*@
                    <div class="row">
                        <section class="col col-6">
                            <label class="input">Status
                                <input type="text"disabled="disabled" name="postion" value="@Model.Position">
                            </label>
                        </section>
                    </div>
                </fieldset>
                <footer>
                    <button type="button" class="btn btn-default" onclick="window.history.back();">Back</button>
                </footer>
            }
         

        </div>
        <!-- end widget content -->

    </div>
    <!-- end widget div -->

</div>
<!-- end widget -->



@section pagespecific {
    <script type="text/javascript">

    // DO NOT REMOVE : GLOBAL FUNCTIONS!

    $(document).ready(function () {

        // START AND FINISH DATE
        $('#startdate').datepicker({
            dateFormat: 'dd/mm/yy',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (selectedDate) {
                $('#finishdate').datepicker('option', 'minDate', selectedDate);
            }
        });

        $('#finishdate').datepicker({
            dateFormat: 'dd/mm/yy',
            prevText: '<i class="fa fa-chevron-left"></i>',
            nextText: '<i class="fa fa-chevron-right"></i>',
            onSelect: function (selectedDate) {
                $('#startdate').datepicker('option', 'maxDate', selectedDate);
            }
        });

        var $orderForm = $("#article-form").validate({
            // Rules for form validation
            rules: {

                position: {
                    required: true
                },
                startdate: {
                    required: true
                },
                finishdate: {
                    required: true
                },
                headline: {
                    required: true
                },
                content: {
                    required: true
                },
            },

            // Messages for form validation
            messages: {

                position: {
                    required: 'Please select your position'
                },
                startdate: {
                    required: 'Please select Valid From Date'
                },
                finishdate: {
                    required: 'Please select Valid From Date'
                },
                headline: {
                    required: 'Please enter your headline'
                },
                content: {
                    required: 'Please input your content'
                }
            },
            // Do not change code below
            errorPlacement: function (error, element) {
                error.insertAfter(element.parent());
            }
        });




    })
    </script>
}