Models/BuildingUtility.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MandiriCRE.Models
{
    public class BuildingUtility
    {
        public string No { get; set; }
        public string BuildingUtilityID { get; set; }
        public string BuildingID { get; set; }
        public string BuildingName { get; set; }
        public string YearID { get; set; }
        public string MonthID { get; set; }
        public string MonthName { get; set; }
        public string Pencadangan { get; set; }
        public string SubjectID { get; set; }
        public string Subject { get; set; }
        public string URCCodeID { get; set; }
        public string URCCode { get; set; }
        public string URCCodeDesc { get; set; }
        public string Invoice { get; set; }
        public string SetOff { get; set; }
        public string FPPDocID { get; set; }
        public string DocFileName { get; set; }
        public string Path { get; set; }
        public string FolderName { get; set; }
        public string CreatedDate { get; set; }
        public string ActionSave { get; set; }
        public string UserName { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }

    }
}

Controllers/BuildingUtilityController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MandiriCRE.Models;
using System.IO;
using System.Data.SqlClient;
using System.Data;
using MandiriCRE.ViewModel;
using System.Web.UI;
using Simplexcel;
using System.Text.RegularExpressions;

namespace MandiriCRE.Controllers
{
    public class BuildingUtilityController : Controller
    {
        string Baseurl = Properties.Settings.Default.BaseURI;
        string Baseurl2 = Properties.Settings.Default.BaseURI;
        // GET: Building Utility
        public async Task<ActionResult> Index()
        {
            var model = new BuildingUtilityIndexViewModel();

            model.InitializePermissions(
                Session,
                "20"
            );

            model.BuildingUtilityJson = await JsonDownloader.GetJsonOrDefaultAsync(
                Baseurl2,
                Properties.Settings.Default.BuildingUtilityAPI,
                EmptyJsonDefault.EmptyArray
            );

            return View(model);
        }

        public async Task<ActionResult> Create(string ErrorMessage, BuildingUtility objBuilding)
        {
            if (ErrorMessage != null)
            {
                ViewBag.ErrorMessage = ErrorMessage;
            }

            List<Building> _listBuilding = await GetListBuilding();
            ViewBag.ListBuilding = _listBuilding;

            List<URCCode> _listURCCode = await GetListURCCode();
            ViewBag.ListURCCode = _listURCCode;

            List<Subject> _listSubject = await GetListSubject();
            ViewBag.ListSubject = _listSubject;

            BuildingUtility objInfo = new BuildingUtility();
            if (objBuilding != null)
            {
                objInfo = objBuilding;
            }
            if (ErrorMessage != null)
            {
                ViewBag.ErrorMessage = ErrorMessage;
            }
            return View(objInfo);
        }

        // POST: BuildingOccupants/Create
        [HttpPost]
        //public async Task<ActionResult> Create(string id, string WF, ProcurementHeader obj, FormCollection collection)
        public async Task<ActionResult> Create(BuildingUtility objBuilding, FormCollection collection, HttpPostedFileBase file)
        {
            try
            {
                BuildingUtility obj = new BuildingUtility();

                obj.BuildingID = collection["BuildingID"].ToString();
                obj.YearID = collection["YearID"].ToString();
                obj.MonthID = collection["MonthID"].ToString();
                obj.SubjectID = collection["SubjectID"].ToString();
                obj.URCCodeID = ""; //req 231018
                obj.URCCodeDesc = ""; //req 231018
                if (collection["URCCodeID"] != null && collection["URCCodeID"] != "")
                {
                    obj.URCCodeID = collection["URCCodeID"].ToString();
                    obj.URCCodeDesc = collection["URCCodeDesc"].ToString();
                }
                obj.Invoice = collection["Invoice"].ToString();
                obj.SetOff = "";
                if (collection["SetOff"] != null && collection["SetOff"] != "")
                {
                    obj.SetOff = collection["SetOff"].ToString();
                }
                obj.ActionSave = "INSERT";
                obj.BuildingUtilityID = "0";
                obj.UserName = User.Identity.Name;

                string ErrorMessage = "";
                string fileName = "";
                string path = "";
                string fileType = "";

                /*DOK 1*/
                if (file == null && (collection["DocumentName"].ToString() != null && collection["DocumentName"].ToString() != ""))
                {
                    fileName = collection["DocumentName"].ToString();
                    obj.DocFileName = fileName;
                    path = Path.Combine(Server.MapPath("~/content/document/buildingutility/"), fileName);
                }
                //Upload File
                /*DOK 1*/
                if (file != null && file.ContentLength > 0)
                {
                    fileType = Path.GetExtension(file.FileName);
                    if (fileType.ToUpper().Contains("PDF"))
                    {
                        if (file.ContentLength <= (5000 * 1024))
                        {
                            fileName = Path.GetFileName(file.FileName);
                            path = Path.Combine(Server.MapPath("~/content/document/buildingutility/"), fileName);
                            file.SaveAs(path);

                            //insert file data
                            obj.DocFileName = fileName;
                            obj.FolderName = "buildingutility";
                            obj.Path = path;
                        }
                        else
                        {
                            ErrorMessage = "File Upload tidak boleh lebih dari 5 MB";
                            return await Create(ErrorMessage, obj);
                        }

                    }
                    else
                    {
                        ErrorMessage = "File Upload harus dengan format PDF";
                        return await Create(ErrorMessage, obj);
                    }
                }


                #region cekduplicate
                BuildingOccupants obj2 = new BuildingOccupants();

                string connectionstring = System.Configuration.ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                using (SqlConnection conn = new SqlConnection(connectionstring))
                {
                    using (var cmd = new SqlCommand("sp_CheckDuplicateBuildingUtility", conn))
                    {
                        cmd.CommandType = CommandType.StoredProcedure;
                        cmd.Parameters.AddWithValue("@BuildingUtilityID", 0);
                        cmd.Parameters.AddWithValue("@BuildingID", obj.BuildingID);
                        cmd.Parameters.AddWithValue("@YearID", obj.YearID);
                        cmd.Parameters.AddWithValue("@MonthID", obj.MonthID);
                        cmd.Parameters.AddWithValue("@URCCodeID", obj.URCCodeID);
                        cmd.Parameters.AddWithValue("@SubjectID", obj.SubjectID);
                        cmd.Parameters.AddWithValue("@Invoice", obj.Invoice);
                        cmd.Parameters.AddWithValue("@SetOff", obj.SetOff);
                        conn.Open();

                        using (var reader = cmd.ExecuteReader())
                        {
                            while (reader.Read())
                            {
                                obj2.BuildingOccupantsID = reader[0].ToString();
                                ErrorMessage = reader[1].ToString();
                            }
                        }
                    }

                }

                if (ErrorMessage != null && ErrorMessage != "")
                {
                    return await Create(ErrorMessage, obj);
                }
                #endregion


                // TODO: Add update logic here
                HttpClient client = new HttpClient();
                client.BaseAddress = new Uri(Baseurl2);
                client.DefaultRequestHeaders.Accept.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage response = await client.PostAsJsonAsync(Properties.Settings.Default.BuildingUtilityAPI + "/" + "0", obj);
                response.EnsureSuccessStatusCode();



                return RedirectToAction("Index");
            }
            catch (Exception ex)
            {
                string err = ex.Message.ToString();
                return View();
            }
        }

        public async Task<ActionResult> Update(string id, string ErrorMessage)
        {
            List<BuildingUtility> objInfo = new List<BuildingUtility>();
            if (ErrorMessage != null)
            {
                ViewBag.ErrorMessage = ErrorMessage;
            }

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl2);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.BuildingUtilityAPI + "/" + id);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<List<BuildingUtility>>(APIResponse);

                }

                List<Building> _listBuilding = await GetListBuilding();
                ViewBag.ListBuilding = _listBuilding;

                List<URCCode> _listURCCode = await GetListURCCode();
                ViewBag.ListURCCode = _listURCCode;

                

                ViewBag.BuildingUtilityID = id;

                BuildingUtility objOne = new BuildingUtility();

                foreach (BuildingUtility Obj in objInfo)
                {

Views/BuildingUtility/PartialBuildingUtility.cshtml
@model MandiriCRE.Models.BuildingUtility
@{
    ViewBag.Title = "PartialBuildingUtility";
}
<div class="jarviswidget well" id="wid-id-3" style="border:hidden" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">
    <!-- widget div-->
    <div>
        <!-- widget content -->
        <div class="widget-body no-padding">
            @using (Html.BeginForm("PartialBuildingUtility", "BuildingUtility", new { ReturnUrl = ViewBag.ReturnUrl },
FormMethod.Post, new { enctype = "multipart/form-data", @class = "smart-form", @id = "BuildingUtility-form" }))
            {

                <header></header>

                <fieldset>
                    <div class="row">
                        <section class="col col-2">
                            <label>Gedung*</label>
                        </section>
                        <section class="col col-6">
                            @{

                                List<SelectListItem> listBuilding = new List<SelectListItem>();
                                List<MandiriCRE.Models.Building> BuildingList = ViewBag.ListBuilding;
                                foreach (var item in BuildingList)
                                {
                                    listBuilding.Add(new SelectListItem
                                    {
                                        Text = item.BuildingName,
                                        Value = item.BuildingID
                                    });
                                }
                            }

                            <label class="select">
                                @Html.DropDownListFor(model => model.BuildingID, listBuilding.OrderBy(x => x.Text), "-- Pilih Gedung --", new { @class = "select", @id = "BuildingID" })
                            </label>
                        </section>



                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>Tahun*</label>
                        </section>
                        <section class="col col-6">
                            <label class="input">
                                <input type="text" class="number3" name="YearID" id="YearID" value=@Model.YearID maxlength="4" placeholder="">
                            </label>
                        </section>
                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>Bulan*</label>
                        </section>
                        <section class="col col-6">
                            @*<select name="MonthID" id="MonthID" style="width: 250px !important; min-width: 250px; max-width: 250px;height: 25px !important;">
                                    <option value="0" selected="" disabled="">--Pilih Bulan--</option>
                                    <option value="1">Januari</option>
                                    <option value="2">Februari</option>
                                    <option value="3">Maret</option>
                                    <option value="4">April</option>
                                    <option value="5">Mei</option>
                                    <option value="6">Juni</option>
                                    <option value="7">Juli</option>
                                    <option value="8">Agustus</option>
                                    <option value="9">September</option>
                                    <option value="10">Oktober</option>
                                    <option value="11">November</option>
                                    <option value="12">Desember</option>
                                </select> <i></i>*@
                            @{
                                List<SelectListItem> listMonth = new List<SelectListItem>();
                                listMonth.Add(new SelectListItem
                                { Text = "Januari", Value = "1" });
                                listMonth.Add(new SelectListItem
                                { Text = "Februari", Value = "2" });
                                listMonth.Add(new SelectListItem
                                { Text = "Maret", Value = "3" });
                                listMonth.Add(new SelectListItem
                                { Text = "April", Value = "4" });
                                listMonth.Add(new SelectListItem
                                { Text = "Mei", Value = "5" });
                                listMonth.Add(new SelectListItem
                                { Text = "Juni", Value = "6" });
                                listMonth.Add(new SelectListItem
                                { Text = "Juli", Value = "7" });
                                listMonth.Add(new SelectListItem
                                { Text = "Agustus", Value = "8" });
                                listMonth.Add(new SelectListItem
                                { Text = "September", Value = "9" });
                                listMonth.Add(new SelectListItem
                                { Text = "Oktober", Value = "10" });
                                listMonth.Add(new SelectListItem
                                { Text = "November", Value = "11" });
                                listMonth.Add(new SelectListItem
                                { Text = "Desember", Value = "12" });

                            }
                            <label class="select">
                                @Html.DropDownListFor(model => model.MonthID, listMonth.OrderBy(x => Convert.ToInt32(x.Value)), "-- Pilih Bulan --", new { @class = "select", @id = "MonthID" })

                            </label>
                        </section>

                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>Perihal*</label>
                        </section>
                        <section class="col col-6">
                            @{

                                List<SelectListItem> listsubject = new List<SelectListItem>();
                                List<MandiriCRE.Models.Subject> SubjectList = ViewBag.ListSubject;
                                foreach (var item in SubjectList)
                                {
                                    listsubject.Add(new SelectListItem
                                    {
                                        Text = item.SubjectName,
                                        Value = item.SubjectID
                                    });
                                }

                            }

                            <label class="select">
                                @Html.DropDownListFor(model => model.SubjectID, listsubject.OrderBy(x => x.Text), "-- Pilih Perihal --", new { @class = "select", @id = "SubjectID" })

                            </label>

                        </section>
                    </div>
                    <div class="row"> 
                        <section class="col col-2">
                            <label>Kode URC</label>
                        </section>
                        <section class="col col-3">
                            @{

                                List<SelectListItem> listURCCode = new List<SelectListItem>();
                                List<MandiriCRE.Models.URCCode> URCCodeList = ViewBag.ListURCCode;
                                foreach (var item in URCCodeList)
                                {
                                    listURCCode.Add(new SelectListItem
                                    {
                                        Text = item.URCCodeName,
                                        Value = item.URCCodeID
                                    });
                                }

                            }

                            <label class="select">
                                @Html.DropDownListFor(model => model.URCCodeID, listURCCode.OrderBy(x => x.Text), "-- Pilih Kode URC --", new { @class = "select", @id = "URCCodeID" })

                            </label>

                        </section>
                        <section class="col col-3">

                            <label class="input">
                                <input type="text" name="URCCodeDesc" id="URCCodeDesc" value="@Model.URCCodeDesc" maxlength="255" placeholder="" disabled="disabled">
                            </label>
                        </section>

                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>Tagihan (Rp)*</label>
                        </section>
                        <section class="col col-6">

                            <label class="input">
                                <input type="text" class="number2" name="Invoice" id="Invoice" value=@Model.Invoice maxlength="255" placeholder="">
                            </label>
                        </section>
                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>Set Off (Rp)*</label>
                        </section>
                        <section class="col col-6">
                            <label class="input">
                                <input type="text" class="number2" name="SetOff" id="SetOff" value=@Model.SetOff maxlength="255" placeholder="">
                            </label>
                        </section>

                    </div>
                    <div class="row">
                        <section class="col col-2">
                            <label>FPP</label>
                        </section>
                        <section class="col col-6">


                            <div class="input input-file">
                                <span class="button"><input id="file" class="input-lg" type="file" name="file" onchange="this.parentNode.nextSibling.value = this.value">Browse</span><input type="text" id="DocumentName" name="DocumentName" value="@Model.DocFileName" placeholder="Pilih Dokumen.." readonly="">
                                *File dalam format PDF maksimum 5 MB
                            </div>
                        </section>
                        <section class="col col-4">
                            Download Lampiran :
                            @{
                                if (Model.DocFileName != "")
                                {
                                    @Html.ActionLink(Model.DocFileName, "Preview", new { docfile = Model.DocFileName })
                                }

                            }
                        </section>

                    </div>

                </fieldset>
                <footer></footer>

                                }
        </div>
        <!-- end widget content -->
    </div>
    <!-- end widget div -->
</div>

Views/BuildingUtility/PartialHistory.cshtml
@model IEnumerable<MandiriCRE.Models.LogHistory>
@{
    ViewBag.Title = "PartialHistory";
}
<!-- NEW WIDGET START -->
<div class="jarviswidget well" id="wid-id-3" style="border:hidden" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">
    <div>
        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body">
            <table id="datatable_fixed_column" class="table table-striped table-bordered" width="100%">
                <thead>
                    <tr>
                        <th data-hide="phone,tablet" class="text-center">Diubah Tanggal</th>
                        <th data-hide="phone,tablet" class="text-center">Diubah Oleh</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>
                                @Html.DisplayFor(modelItem => item.UpdatedDate)
                            </td>
                            <td>
                                @Html.DisplayFor(modelItem => item.UpdatedBy)
                            </td>
                        </tr>
                    }
                </tbody>
            </table>
        </div>
        <!-- end widget content -->
    </div>
</div>

Views/BuildingUtility/Preview.cshtml
@model MandiriCRE.Models.BuildingUtility
@{
    ViewBag.Title = "Preview";
}

<div class="text-left">

    <button type="button" class="btn btn-primary" style="padding: 8px 25px;" onclick="window.history.back();">Kembali</button>
</div>
<br />
<div>
    <iframe id="iframepdf" src="~/content/document/buildingutility/@ViewBag.DocFile#view=fit" width="1200px" height="1600px"></iframe>
</div>

Views/BuildingUtility/View.cshtml
@model MandiriCRE.Models.BuildingUtility
@{
    ViewBag.Title = "Update";
}


<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa fa-edit"></i>
                Data
                <span>
                    >
                    Utilitas Gedung
                </span>
            </h1>
        </div>
    </div>
    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget well" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">
        <header>
            <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
            <h2> </h2>
        </header>
        <!-- widget div-->
        <div>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="ace-icon fa fa-times"></i>
                    </button>
                    @Html.Raw(ViewBag.ErrorMessage)
                </div>
            }
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
                @using (Html.BeginForm("Update", "BuildingUtility", new { ReturnUrl = ViewBag.ReturnUrl },
        FormMethod.Post, new { enctype = "multipart/form-data", @class = "smart-form", @id = "BuildingUtility-form" }))
                {
                    <div class="text-right">
                        <button class="btn btn-primary" type="button" style="padding: 8px 25px;" onclick="location.href='@Url.Action("Index", "BuildingUtility")'">Kembali</button>
                    </div>



                    <hr class="simple">
                    <ul id="myTab1" class="nav nav-tabs bordered">

                        <li class="active">
                            <a href="#s1" data-toggle="tab">Utilitas Gedung</a>
                        </li>
                        <li>
                            <a href="#s2" data-toggle="tab">Riwayat</a>
                        </li>

                    </ul>

                    <div id="myTabContent1" class="tab-content padding-10">
                        <div class="tab-pane fade in active" id="s1">
                            @{
                                List<MandiriCRE.Models.Building>
                                       BuildingList = ViewBag.ListBuilding;
                                List<MandiriCRE.Models.Subject>
                                    SubjectList = ViewBag.ListSubject;
                                List<MandiriCRE.Models.URCCode>
                                    URCCodeList = ViewBag.ListURCCode;
                            }
                            @{Html.RenderAction("PartialBuildingUtilityView", new { obj = ViewBag.objInfo, _listBuilding = BuildingList, _listSubject = SubjectList, _listURCCode = URCCodeList });}
                        </div>
                        <div class="tab-pane fade" id="s2">
                            @{
                                List<MandiriCRE.Models.LogHistory>
                                ListHist = new List<LogHistory>();
                                ListHist = ViewBag.ListHistory;
                            }
                            @{Html.RenderPartial("PartialHistory", ListHist);}
                        </div>


                    </div>
                                }
            </div>
            <!-- end widget content -->
        </div>
        <!-- end widget div -->
    </div>
    <!-- end widget -->
</div>