Models/Tax.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MandiriCRE.Models
{
    public class Tax
    {
        public string No { get; set; }
        public string TaxID { get; set; }
        public string GLID { get; set; }
        public string GLName { get; set; }
        public string PaymentID { get; set; }
        public string OtherPayment { get; set; }
        public string PaymentName { get; set; }
        public string TaxYearID { get; set; }
        public string TaxYear { get; set; }
        public string IDSAP { get; set; }
        public string FinanceReport { get; set; }
        public string ATTBTypeID { get; set; }
        public string ATTBType { get; set; }
        public string ATTBName { get; set; }
        public string Branch { get; set; }
        public string RegionAssetID { get; set; }
        public string RegionAsset { get; set; }
        public string NOP { get; set; }
        public string ObjectLocation { get; set; }
        public string Kelurahan { get; set; }
        public string Kecamatan { get; set; }
        public string City { get; set; }
        public string TaxPayerName { get; set; }
        public string TaxPayerAddress { get; set; }
        public string TaxPaid { get; set; }
        public string PaidBy { get; set; }
        public string Desciption { get; set; }
        public string TaxDocID { get; set; }
        public string DocFileName { get; set; }
        public string DocFileName2 { get; set; }
        public string DocFileName3 { get; set; }
        public string Path { get; set; }
        public string FolderName { get; set; }
        public string BuildingArea { get; set; }
        public string BuildingNJOP { get; set; }
        public string BuildingClass { get; set; }
        public string LandArea { get; set; }
        public string LandNJOP { get; set; }
        public string LandClass { get; set; }
        public string UserName { get; set; }
        public string ActionSave { get; set; }

        public string CreatedDate { get; set; }
        public string CreatedBy { get; set; }
        public string UpdatedDate { get; set; }
        public string UpdatedBy { get; set; }
        public string UpdatedDateReal { get; set; }
        public DateTime UpdatedDateRealDate { get; set; }

    }
}

Controllers/TaxController.cs
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using MandiriCRE.Models;
using System.IO;
using System.Data.SqlClient;
using System.Data;
using System.Web.UI;
using Simplexcel;
using System.Text.RegularExpressions;
using System.Globalization;
using MandiriCRE.ViewModel;
//using Microsoft.Office.Interop.Excel;

namespace MandiriCRE.Controllers
{

    public class TaxController : Controller
    {

        string Baseurl = Properties.Settings.Default.BaseURI;
        string Baseurl2 = Properties.Settings.Default.BaseURI;

        //public Microsoft.Office.Interop.Excel.Page Page { get; private set; }
        public object Controls { get; private set; }

        // GET: Tax
        public async Task<ActionResult> Index()
        {
            var model = new TaxIndexViewModel();

            var sessionAccessString = Session["Access"]?.ToString();

            var isSuperAdmin = sessionAccessString == "superadmin";

            if (isSuperAdmin)
            {
                model.IsAllowedToView = true;
                model.IsAllowedToUpdate = true;
                model.IsAllowedToDelete = true;
                model.IsAllowedToDuplicate = true;
            }

            if (!string.IsNullOrWhiteSpace(sessionAccessString))
            {
                var index = sessionAccessString.IndexOf("19");
                var allowedToViewString = sessionAccessString.Substring(index + 2, 1);
                if (allowedToViewString == "Y")
                {
                    model.IsAllowedToView = true;
                }
                var allowedToUpdateString = sessionAccessString.Substring(index + 4, 1);
                if (allowedToUpdateString == "Y")
                {
                    model.IsAllowedToUpdate = true;
                }
                var allowedToDeleteString = sessionAccessString.Substring(index + 5, 1);
                if (allowedToDeleteString == "Y")
                {
                    model.IsAllowedToDelete = true;
                }
                var allowedToDuplicateString = sessionAccessString.Substring(index + 6, 1);
                if (allowedToDuplicateString == "Y")
                {
                    model.IsAllowedToDuplicate = true;
                }
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(Baseurl2);
                client.DefaultRequestHeaders.Clear();
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                var res = await client.GetAsync(Properties.Settings.Default.TaxAPI);

                if (res.IsSuccessStatusCode)
                {
                    model.TaxesJson = res.Content.ReadAsStringAsync().Result;
                }
                return View(model);
            }
        }

        // GET: Tax/TaxID
        public async Task<ActionResult> Details(string id)
        {
            Tax objInfo = new Tax();

            using (var client = new HttpClient())
            {
                //Passing service base url  
                client.BaseAddress = new Uri(Baseurl2);

                client.DefaultRequestHeaders.Clear();
                //Define request data format  
                client.DefaultRequestHeaders.Accept.Add(new MediaTypeWithQualityHeaderValue("application/json"));

                //Sending request to find web api REST service resource GetAllArticles using HttpClient  
                HttpResponseMessage Res = await client.GetAsync(Properties.Settings.Default.TaxAPI + "/" + id);

                //Checking the response is successful or not which is sent using HttpClient  
                if (Res.IsSuccessStatusCode)
                {
                    //Storing the response details recieved from web api   
                    var APIResponse = Res.Content.ReadAsStringAsync().Result;

                    //Deserializing the response recieved from web api and storing into the Employee list  
                    objInfo = JsonConvert.DeserializeObject<Tax>(APIResponse);

                }
                ViewBag.TaxID = id;
                return View(objInfo);
            }
        }

        //GET: Procurement/Create
        //public async Task<ActionResult> Create(string id, string Status, string WF, string ErrorMessage)
        public async Task<ActionResult> Create(string ErrorMessage, Tax objTax)
        {
            if (ErrorMessage != null)
            {
                ViewBag.ErrorMessage = ErrorMessage;
            }

            List<GL> _listGL = await GetListGL();
            ViewBag.ListGL = _listGL;

            List<Payment> _listPayments = await GetListPayment();
            ViewBag.ListPayments = _listPayments;

            List<ATTBTypeModels> _listATTBType = await GetListATTBType();
            ViewBag.ListATTBType = _listATTBType;

            List<RegionAssetModels> _listRegionAsset = await GetListRegionAsset();
            ViewBag.ListRegionAsset = _listRegionAsset;

            List<YearTax> _listTaxYear = await GetListTaxYear();
            ViewBag.ListTaxYear = _listTaxYear;

            Tax objInfo = new Tax();
            if (objTax != null)
            {
                objInfo = objTax;
            }
            if (ErrorMessage != null)
            {
                ViewBag.ErrorMessage = ErrorMessage;
            }
            return View(objInfo);
        }
        // POST: Procurement/Create
        [HttpPost]
        //public async Task<ActionResult> Create(string id, string WF, ProcurementHeader obj, FormCollection collection)
        public async Task<ActionResult> Create(Tax objTax, FormCollection collection, HttpPostedFileBase file, HttpPostedFileBase file2, HttpPostedFileBase file3)
        {
            try
            {
                String ListFileName = "";
                Tax obj = new Tax();

                obj.GLID = collection["GLID"].ToString();
                //obj.GLName = collection["gLName"].ToString();
                obj.PaymentID = collection["PaymentName"].ToString();
                if ((collection["OtherPayment"] != null && collection["OtherPayment"] != "") || (obj.OtherPayment != null && obj.OtherPayment != "") || (ViewBag.OtherPayment != null && ViewBag.OtherPayment != ""))
                {
                    obj.PaymentID = collection["OtherPayment"];
                    obj.OtherPayment = collection["OtherPayment"];
                    ViewBag.OtherPayment = collection["OtherPayment"];
                }
                obj.TaxYearID = collection["TaxYearID"].ToString();
                //obj.TaxYear = collection["taxYear"].ToString();
                obj.IDSAP = collection["iDSAP"].ToString();
                obj.FinanceReport = collection["financeReport"].ToString();
                obj.ATTBTypeID = collection["ATTBTypeID"].ToString();
                //obj.ATTBType = collection["aTTBType"].ToString();
                obj.ATTBName = collection["aTTBName"].ToString();
                if ((collection["branch"] != null && collection["branch"] != ""))
                {
                    obj.Branch = collection["branch"].ToString();
                }  
                obj.RegionAssetID = collection["RegionAssetID"].ToString();
                //obj.RegionAsset = collection["regionAsset"].ToString();
                obj.NOP = collection["nOP"].ToString();
                obj.ObjectLocation = collection["objectLocation"].ToString();
                obj.Kelurahan = collection["kelurahan"].ToString();
                obj.Kecamatan = collection["kecamatan"].ToString();
                obj.City = collection["city"].ToString();
                obj.TaxPayerName = collection["taxPayerName"].ToString();
                obj.TaxPayerAddress = collection["taxPayerAddress"].ToString();
                obj.TaxPaid = collection["taxPaid"].ToString();
                obj.PaidBy = collection["paidBy"].ToString();
                obj.Desciption = collection["desciption"].ToString();
                obj.BuildingArea = collection["buildingArea"].ToString();
                obj.BuildingNJOP = collection["buildingNJOP"].ToString();
                obj.BuildingClass = collection["buildingClass"].ToString();
                obj.LandArea = collection["landArea"].ToString();
                obj.LandNJOP = collection["landNJOP"].ToString();
                obj.LandClass = collection["landClass"].ToString();
                if (collection["docFileName"] != null && collection["docFileName"] != "")
                {
                    obj.DocFileName = collection["docFileName"];
                }
                if (collection["docFileName2"] != null && collection["docFileName2"] != "")
                {
                    obj.DocFileName2 = collection["docFileName2"];
                }
                if (collection["docFileName3"] != null && collection["docFileName3"] != "")
                {
                    obj.DocFileName3 = collection["docFileName3"];
                }
                obj.ActionSave = "INSERT";
                obj.TaxID = "0";
                obj.UserName = User.Identity.Name;

                string ErrorMessage = "";
                string fileName = "";
                string path = "";
                string fileType = "";
                //Upload File -1-
                if (file != null && file.ContentLength > 0)
                {
                    fileType = Path.GetExtension(file.FileName);
                    if (fileType.ToUpper().Contains("DOC") || fileType.ToUpper().Contains("XLS") || fileType.ToUpper().Contains("PDF"))
                    {
                            fileName = Path.GetFileName(file.FileName);
                            path = Path.Combine(Server.MapPath("~/content/document/tax/"), fileName);

Views/Tax/Delete.cshtml
@model MandiriCRE.Models.Tax
@{
    ViewBag.Title = "Delete";
}



<h2></h2>
<!-- Widget ID (each widget will need unique ID)-->
<div class="jarviswidget" id="wid-id-3" data-widget-editbutton="false" data-widget-custombutton="false">
    <header>
        <span class="widget-icon"> <i class="fa fa-edit"></i> </span>
    </header>
    <!-- widget div-->
    <div>
        <!-- widget edit box -->
        <div class="jarviswidget-editbox">
            <!-- This area used as dropdown edit box -->
        </div>
        <!-- end widget edit box -->
        <!-- widget content -->
        <div class="widget-body no-padding">
            @using (Html.BeginForm("Delete", "Tax",
            new { ReturnUrl = ViewBag.ReturnUrl, id = ViewBag.TaxID },
            FormMethod.Post, new { @class = "smart-form", @id = "numbering-form" }))
            {
                <header>
                    <b> Apakah Anda yakin akan menghapus data ini ?</b>
                </header>

                <div class="text-right">
                    <button class="btn btn-primary" name="Sign" type="submit" style="padding: 8px 25px;">Hapus</button>
                    <button class="btn btn-primary" type="button" style="padding: 8px 25px;" onclick="location.href='@Url.Action("Index", "Tax")'">Batal</button>
                </div>

                <fieldset>
                    @{
                        List<MandiriCRE.Models.GL>
                               GLList = ViewBag.ListGL;
                        List<MandiriCRE.Models.Payment>
                            paymentList = ViewBag.ListPayments;
                        List<MandiriCRE.Models.ATTBTypeModels>
                            ATTBTypeList = ViewBag.ListATTBType;
                        List<MandiriCRE.Models.RegionAssetModels>
                            regionAssetList = ViewBag.ListRegionAsset;
                        List<MandiriCRE.Models.YearTax>
                            yearTaxList = ViewBag.ListTaxYear;

                    }
                    @{Html.RenderAction("PartialTaxView", new { obj = ViewBag.objInfo, _listGL = GLList, _listPayment = paymentList, _listATTBType = ATTBTypeList, _listRegionAsset = regionAssetList, _listyearTax = yearTaxList });}


                </fieldset>
                <footer>
                    @*<input type="submit" value="Hapus" class="btn btn-primary btn-lg" />
                    <button type="button" class="btn btn-default" onclick="window.history.back();">Batal</button>*@
                </footer>
            }
        </div>
        <!-- end widget content -->
    </div>
    <!-- end widget div -->
</div>
<!-- end widget -->


@*<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <b> Apakah Anda yakin akan menghapus data ini ?</b>
            </h1>
        </div>
    </div>
    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget well" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">
        
            <header>
                <b> Apakah Anda yakin akan menghapus data ini ?</b>
            </header>

        
        <!-- widget div-->
        <div>
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            @using (Html.BeginForm("View", "Tax",
            new { ReturnUrl = ViewBag.ReturnUrl },
            FormMethod.Post, new { @class = "smart-form", @id = "tax-form" }))
            {
                <div class="widget-body">
                    <div class="text-right">
                        <button class="btn btn-primary" name="Sign" type="submit" style="padding: 8px 25px;">Hapus</button>
                        <button class="btn btn-primary" type="button" onclick="location.href='@Url.Action("Index", "Tax" )'" style="padding: 8px 25px;">Batal</button>
                    </div>
                    <hr class="simple">
                    <ul id="myTab1" class="nav nav-tabs bordered">
                        <li class="active">
                            <a href="#s1" data-toggle="tab">Tax</a>
                        </li>
                        <li>
                            <a href="#s2" data-toggle="tab">Riwayat</a>
                        </li>
                    </ul>
                    <div id="myTabContent1" class="tab-content padding-10">
                        <div class="tab-pane fade in active" id="s1">
                            @{
                                List<MandiriCRE.Models.GL>
                                       GLList = ViewBag.ListGL;
                                List<MandiriCRE.Models.Payment>
                                    paymentList = ViewBag.ListPayments;
                                List<MandiriCRE.Models.ATTBTypeModels>
                                    ATTBTypeList = ViewBag.ListATTBType;
                                List<MandiriCRE.Models.RegionAssetModels>
                                    regionAssetList = ViewBag.ListRegionAsset;
                                List<MandiriCRE.Models.YearTax>
                                    yearTaxList = ViewBag.ListTaxYear;

                            }
                            @{Html.RenderAction("PartialTaxView", new { obj = ViewBag.objInfo, _listGL = GLList, _listPayment = paymentList, _listATTBType = ATTBTypeList, _listRegionAsset = regionAssetList, _listyearTax = yearTaxList });}

                        </div>

                        <div class="tab-pane fade" id="s2">
                            @{
                                List<MandiriCRE.Models.LogHistory>
                                ListHist = new List<LogHistory>();
                                ListHist = ViewBag.ListHistory;
                            }
                            @{Html.RenderPartial("PartialHistory", ListHist);}
                        </div>
                    </div>
                </div>
            <!-- end widget content -->
                                }
        </div>
        <!-- end widget div -->
    </div>
    <!-- end widget -->
</div>*@

Views/Tax/Duplicate2.cshtml
@model MandiriCRE.Models.Tax
@{
    ViewBag.Title = "Duplicate2";
}


<div id="content">
    <div class="row">
        <div class="col-xs-12 col-sm-7 col-md-7 col-lg-4">
            <h1 class="page-title txt-color-blueDark">
                <i class="fa fa-edit"></i>
                Data
                <span>
                    >
                    Tax
                </span>
            </h1>
        </div>
    </div>
    <!-- Widget ID (each widget will need unique ID)-->
    <div class="jarviswidget well" id="wid-id-3" data-widget-colorbutton="false" data-widget-editbutton="false" data-widget-togglebutton="false" data-widget-deletebutton="false" data-widget-fullscreenbutton="false" data-widget-custombutton="false" data-widget-sortable="false">
        <header>
            <span class="widget-icon"> <i class="fa fa-comments"></i> </span>
            <h2> </h2>
        </header>
        <!-- widget div-->
        <div>
            @if (ViewBag.ErrorMessage != null)
            {
                <div class="alert alert-danger">
                    <button type="button" class="close" data-dismiss="alert">
                        <i class="ace-icon fa fa-times"></i>
                    </button>
                    @Html.Raw(ViewBag.ErrorMessage)
                </div>
            }
            <!-- widget edit box -->
            <div class="jarviswidget-editbox">
                <!-- This area used as dropdown edit box -->
            </div>
            <!-- end widget edit box -->
            <!-- widget content -->
            <div class="widget-body">
                @using (Html.BeginForm("Duplicate2", "Tax", new { ReturnUrl = ViewBag.ReturnUrl },
                FormMethod.Post, new { enctype = "multipart/form-data", @class = "smart-form", @id = "tax-form" }))
                {
                    <div class="text-right">
                        <button class="btn btn-primary" name="Sign" type="submit" style="padding: 8px 25px;">Duplicate</button>
                        <button class="btn btn-primary" type="button" style="padding: 8px 25px;" onclick="location.href='@Url.Action("Index", "Tax")'">Kembali</button>
                    </div>



                        <hr class="simple">
                        <ul id="myTab1" class="nav nav-tabs bordered">

                            <li class="active">
                                <a href="#s1" data-toggle="tab">Tax</a>
                            </li>
                            @*<li>
                                <a href="#s2" data-toggle="tab">Riwayat</a>
                            </li>*@

                        </ul>

                        <div id="myTabContent1" class="tab-content padding-10">
                            <div class="tab-pane fade in active" id="s1">
                                @{
                                    List<MandiriCRE.Models.GL>
                                           GLList = ViewBag.ListGL;
                                    List<MandiriCRE.Models.Payment>
                                        paymentList = ViewBag.ListPayments;
                                    List<MandiriCRE.Models.ATTBTypeModels>
                                        ATTBTypeList = ViewBag.ListATTBType;
                                    List<MandiriCRE.Models.RegionAssetModels>
                                        regionAssetList = ViewBag.ListRegionAsset;
                                    List<MandiriCRE.Models.YearTax>
                                        yearTaxList = ViewBag.ListTaxYear;
                                }
                                @{Html.RenderAction("PartialTax", new { obj = ViewBag.objInfo, _listGL = GLList, _listPayment = paymentList, _listATTBType = ATTBTypeList, _listRegionAsset = regionAssetList, _listyearTax = yearTaxList });}
                            </div>
                            @*<div class="tab-pane fade" id="s2">
                                @{
                                    List<MandiriCRE.Models.LogHistory>
                                    ListHist = new List<LogHistory>();
                                    ListHist = ViewBag.ListHistory;
                                }
                                @{Html.RenderPartial("PartialHistory", ListHist);}
                            </div>*@


                        </div>
                                    }
            </div>
            <!-- end widget content -->
        </div>
        <!-- end widget div -->
    </div>
    <!-- end widget -->
</div>

@section pagespecific {
    <script type="text/javascript">

        // DO NOT REMOVE : GLOBAL FUNCTIONS!

        $(document).ready(function () {

            // Number Fields
            $('input.number2').keyup(function (event) {

                // skip for arrow keys
                if (event.which >= 37 && event.which <= 40) return;

                // format number
                $(this).val(function (index, value) {
                    return value
                    .replace(/\D/g, "")
                    .replace(/\B(?=(\d{3})+(?!\d))/g, ".")
                    ;
                });
            });

            if(($('#aTTBTypeID').val())== "1")
            {
                $('#branch').removeAttr('disabled');
                $('#branch').attr("required", "true");
            };



            $('#aTTBTypeID').change(function () {
                //var varpic = $(this).Text();
                var varpic = $(this).val();
                if (varpic == "1") {
                    $('#branch').removeAttr('disabled');
                    $('#branch').attr("required", "true");
                }
                else {
                    $('#branch').attr('disabled', 'disabled');
                    $('#branch').removeAttr("required");
                }
            });

            $('#PaymentName').change(function () {
                var varpayment = $(this).val();
                if (varpayment == "0") {
                    $('#OtherPayment').removeAttr('disabled');
                    $('#OtherPayment').attr("required", "true");
                }
                else {
                    $('#OtherPayment').attr('disabled', 'disabled');
                    $('#OtherPayment').removeAttr("required");
                }
            });


            var $numberingForm = $("#tax-form").validate({
                // Rules for form validation
                rules: {
                    GLID: {
                        required: true
                    },
                    PaymentName: {
                        required: true
                    },
                    TaxYearID: {
                        required: true
                    },
                    iDSAP: {
                        required: true
                    },
                    financeReport: {
                        required: true
                    },
                    ATTBTypeID: {
                        required: true
                    },
                    aTTBName: {
                        required: true
                    },
                    branch: {
                        required: false
                    },
                    RegionAssetID: {
                        required: true
                    },
                    nOP: {
                        required: true
                    },
                    objectLocation: {
                        required: true
                    },
                    kelurahan: {
                        required: true
                    },
                    kecamatan: {
                        required: true
                    },
                    city: {
                        required: true
                    },
                    taxPayerName: {
                        required: true
                    },
                    taxPayerAddress: {
                        required: true
                    },
                    taxPaid: {
                        required: true
                    },
                    paidBy: {
                        required: true
                    },
                    desciption: {
                        required: false
                    },
                    buildingArea: {
                        required: true
                    },
                    buildingNJOP: {
                        required: true
                    },
                    buildingClass: {
                        required: true
                    },
                    landArea: {
                        required: true
                    },
                    landNJOP: {
                        required: true
                    },
                    landClass: {
                        required: true
                    },
                    docFileName: {
                        required: false
                    }
                },

                // Messages for form validation
                messages: {
                    GLID: {
                        required: 'Silahkan pilih GL'
                    },
                    PaymentName: {
                        required: 'Silahkan pilih Pembayaran'
                    },
                    TaxYearID: {
                        required: 'Silahkan pilih Tahun'
                    },
                    iDSAP: {
                        required: 'Silahkan isi ID SAP'
                    },
                    financeReport: {
                        required: 'Silahkan isi Lap Keu'
                    },
                    ATTBTypeID: {
                        required: 'Silahkan pilih Tipe ATTB'
                    },
                    aTTBName: {
                        required: 'Silahkan isi Nama ATTB'
                    },
                    branch: {
                        required: 'Silahkan isi Cabang'
                    },
                    RegionAssetID: {
                        required: 'Silahkan pilih Region'
                    },
                    nOP: {
                        required: 'Silahkan isi NOP'
                    },
                    objectLocation: {
                        required: 'Silahkan isi Lokasi Objek'
                    },
                    kelurahan: {
                        required: 'Silahkan isi Kelurahan'
                    },
                    kecamatan: {
                        required: 'Silahkan isi Kecamatan'
                    },
                    city: {
                        required: 'Silahkan isi Kota'
                    },
                    taxPayerName: {
                        required: 'Silahkan isi Nama Wajib Pajak'
                    },
                    taxPayerAddress: {
                        required: 'Silahkan isi Alamat Wajib Pajak'
                    },
                    taxPaid: {
                        required: 'Silahkan isi Pajak Dibayar'
                    },
                    paidBy: {
                        required: 'Silahkan isi DIbayar'
                    },
                    desciption: {
                        required: 'Silahkan isi Keterangan'
                    },
                    buildingArea: {
                        required: 'Silahkan isi Luas Bangunan'
                    },
                    buildingNJOP: {
                        required: 'Silahkan isi NJOP '
                    },
                    buildingClass: {
                        required: 'Silahkan isi Kelas '
                    },
                    landArea: {
                        required: 'Silahkan isi Luas Tanah'
                    },
                    landNJOP: {
                        required: 'Silahkan isi NJOP'
                    },
                    landClass: {
                        required: 'Silahkan isi Kelas'
                    }
                },
            });



        })
    </script>
}

Views/Tax/Preview.cshtml
@model MandiriCRE.Models.Tax
@{
    ViewBag.Title = "Preview";
}

    @*<iframe src="https://docs.google.com/viewer?url=~/content/document/tax/TEST TAX DOC.pdf&embedded=true"></iframe>*@

@*<iframe id="fred" style="border:1px solid #666CCC" title="PDF in an i-Frame" src="PDFData.pdf" frameborder="1" scrolling="auto" height="1100" width="850">*@

<div class="text-left">
    
    <button type="button" class="btn btn-primary" style="padding: 8px 25px;" onclick="window.history.back();">Kembali</button>
</div> 
<br/>
<div>
    <iframe id="iframepdf" src="~/content/document/tax/@ViewBag.DocFile#view=fit"  width="1200px" height="1600px"></iframe>
</div>   
   